# Generated by Django 2.0.5 on 2018-05-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CnnModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_path', models.CharField(max_length=512)),
                ('nn_type', models.CharField(max_length=32)),
            ],
        ),
    ]
