# Generated by Django 2.0.5 on 2018-05-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnnmodel',
            name='layer_iterations',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cnnmodel',
            name='number_of_epoch',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
