# Generated by Django 2.0.5 on 2018-05-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ui', '0002_auto_20180512_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnnmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
