# Generated by Django 2.0.5 on 2018-05-13 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ui', '0003_auto_20180512_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cnnmodel',
            old_name='project_path',
            new_name='nn_path',
        ),
        migrations.RemoveField(
            model_name='cnnmodel',
            name='layer_iterations',
        ),
        migrations.RemoveField(
            model_name='cnnmodel',
            name='nn_type',
        ),
        migrations.RemoveField(
            model_name='cnnmodel',
            name='number_of_epoch',
        ),
    ]
