# Generated by Django 2.0.5 on 2018-05-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ui', '0004_auto_20180513_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CnnModel',
        ),
    ]
